"""remove user_id from tenant

Revision ID: 812f42f7c73b
Revises: 7437fde34cd7
Create Date: 2026-05-27 10:55:35.546289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812f42f7c73b'
down_revision: Union[str, Sequence[str], None] = '7437fde34cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tenants_user_id_key'), 'tenants', type_='unique')
    op.drop_constraint(op.f('tenants_user_id_fkey'), 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tenants_user_id_fkey'), 'tenants', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('tenants_user_id_key'), 'tenants', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
